# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d9f02a548601b20a775d7f690f2431ae306ece7d3d1415f440dd1443f001a77d75ba1e29377fba851fab20709ffbb6e8edba12f1b2de4650355aea06eb1521

test:
  secret_key_base: ea34508c5111b0d68846d1e2d4d11edcc052286ad62a19674b2b0a72dae714e094f8bf67c04f599be179ef532a62db5684d67d8f2580eca6def2b67af7f5c92c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
